name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: echo "Hello GitHub Actions"
        
      - name: Step1
        run: echo "Hello from Step1"

      - name: Step2
        run: echo "Hello from Step2"


